### ISSUE TITLE
Import Order Causes Excluded Entries to Be Processed

### ISSUE THREAD

**Issue by ErickKramer** [ErickKramer/ripvcs#23]
## Description

Given the following `.repos` files 

`nested_example.repos`

```yaml
repositories:
  a/twist_mux: # Make it appear at the top when sorted
    type: git
    url: https://github.com/ros-teleop/twist_mux.git
    version: humble
    exclude: [twist_mux_deps.repos]
  twist_mux_2/stuff:
    type: git
    url: https://github.com/ros-teleop/twist_mux.git
    version: humble
    exclude: [stuff]
```

`nested_example2.repos`

```
repositories:
  ripvcs:
    type: git
    url: https://github.com/ErickKramer/ripvcs.git
    exclude:
      - invalid_example.repos
      - valid_example.repos
      - valid_example.rosinstall
```

When running:

`go run main.go import -i ./test/nested_example2.repos /tmp/example --recursive`

twice, the second execution imports from a/twist_mux before processing the exclude entries listed in `nested_example2.repos`. This happens due to the order in which .repos files are read, causing excluded repositories to be imported when they shouldn't be.

## Expected Behavior

Excluded repositories should not be imported, regardless of the order in which .repos files are read.

## Actual Behavior

During the second execution, a/twist_mux is processed before the exclusion rules are applied, leading to an unintended import.

## Suggested Fix

One possible solution would be to refactor the import command to process all the found `.repos` files that are not explicitly excluded by the `--exclude` argument and get the additional exclude entries from them before processing them.
